### ISSUE TITLE
Windows peers are creating a 200 ms delay between TCP transmissions 

### ISSUE THREAD

**Issue by mguentner** [ethersex/ethersex#257] opened 2013-07-23 00:10 UTC
The Windows TCP/IP stack uses Nagle's algorithm to improve efficiency.
However it has a fixed timeout of 200 ms rather than dynamic one.
Since uip/ethersex only supports sending a packet once the ACK has been received, each TCP packet will be delayed by 200 ms.
This only happens of course when the TCP stream consists of more than one (data) packet. (long ecmd outputs and most HTTP requests) 

Example: ```help``` via telnet

Since each newline leads to a new tcp packet, we get a delay of ```COMMANDS_AVAILABLE*(0.2s+AVG_TRANSMISSION_TIME)```

Example:
20 Commands, 20 ms Transmission Time (roundtrip)
```20*0.22s=4.4s``` Delay for one command

This also happens when using the HTTP ECMD interface.
=> one ajax request takes up to several seconds!

We have some options here:

* use uip-split where each outgoing TCP packet will be split into two smaller ones and forcing the Windows peer to transmit one ACK immediately.
* transmit each TCP packet twice
* ignore that Windows users exist (and force them to manually set TCP_NODELAY)

References:
* http://support.microsoft.com/kb/214397/en
* http://www.nuttx.org/doku.php?id=wiki:networking:delayedacks#uip_delayed_acks_and_split_packets
* http://en.wikipedia.org/wiki/Nagle%27s_algorithm

**Comment by lukasfischer83** [comment] 2015-04-14 13:10
Hi, I tried to test it on win XP, i can see the additional ACK in wireshark on linux, but the performance issue is still there when receiving answers consisting of multiple packages. Any hints?

**Comment by lukasfischer83** [comment] 2015-04-14 14:34
![screenshot from 2015-04-14 16 31 38](https://cloud.githubusercontent.com/assets/10271325/7138988/ff96e27c-e2c3-11e4-97a3-34d6f70370f0.png)
Here is the wireshark log of the transmission, you can still see the ~200ms delay after ethersex sent the extra ACK frame.

**Comment by eku** [comment] 2015-04-14 17:02
AFAIK the delay problem has gone with Windows 7. Who is still using XP these days?

**Comment by michaelb42** [comment] 2015-04-14 18:51
@eku: No, it hasn't. I still can reproduce this problem with Win7 with all patches and service packs.

**Comment by eku** [comment] 2015-04-15 06:27
Did you try the registry modification as suggested by MS?
https://github.com/ethersex/ethersex/issues/257#issuecomment-42289273

**Comment by lukasfischer83** [comment] 2015-04-15 08:13
Yes I did, it works, but you can't expect a regular user to do this modification on every machine he wants to use an ethersex based device on.
I'm not an expert in this, but is there a difference between an empty TCP packet and an ACK? Since MS states in https://support.microsoft.com/en-us/kb/214397/ that it acks after every second received packet, it might work to send an empty packet instead of the ACK.
What would happen if the client program responded with a dummy packet immediately after each received packet? Wouldn't that trigger the automatic "piggybacking" of the ACK by the Windows TCP Stack? I'm using ecmd over TCP, would it be possible to ignore these dummy packages during active repeated transmissions? This would not solve the issues in browsers, but it would at least be a way to speed up direct TCP based connections...

**Comment by eku** [comment] 2015-04-15 13:23
What du you mean with dummy packet? A TCP paket with just flag set? That's exactly what the duplicate ACK is.

**Comment by michaelb42** [comment] 2015-05-25 15:20
There is strong evidence that the problem described above has a cause unrelated to the suspicious delayed acks. The new scheduler from branch https://github.com/ethersex/ethersex/tree/new_timer_framework seems to resolve the problem. ECMD "help", http server, etc. are amazingly fast with no visible delay .

Please test and report back all results and all further problems.

**Comment by eku** [comment] 2015-08-14 18:29
I guess we should close this issue. Any comments?

**Comment by lukasfischer83** [comment] 2015-08-14 19:03
I tried the delayed ack patch but had no success. Longer messages just
timed out then. The issue is still there and can be easily reproduced on
recent versions of windows. Just call the ecmd help via browser, you will
see the entries appearing line by line. Thus is not the case in ubuntu.
Am 14.08.2015 20:29 schrieb "Erik Kunze" <notifications@github.com>:

**Comment by eku** [comment] 2015-09-10 11:43
@lukasfischer83 wrote:
> I'll try next week and report back then.

Any news?

**Comment by eku** [comment] 2015-09-25 13:18
No feedback.

**Closed by eku** 2015-09-25 13:18 UTC
Labels: enhancement
